using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Porticle.Enumly
{

    [Generator]
    public sealed class EnumlyGenerator : IIncrementalGenerator
    {
        private const string EnumlyClassAttributeFqn = "Porticle.Enumly.EnumlyClassAttribute";
        private const string EnumlyMapAttributeFqn = "Porticle.Enumly.EnumlyMapAttribute";
        private const string EnumlyMapValueAttributeFqn = "Porticle.Enumly.EnumlyMapValueAttribute";
        private const string EnumlyIgnoreSourceAttributeFqn = "Porticle.Enumly.EnumlyIgnoreSourceAttribute";
        private const string EnumlyIgnoreTargetAttributeFqn = "Porticle.Enumly.EnumlyIgnoreTargetAttribute";

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace Porticle.Enumly
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class EnumlyClassAttribute : global::System.Attribute { }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class EnumlyMapAttribute : global::System.Attribute
    {
        /// <summary>
        /// Value of the source enum that should be mapped to <c>null</c> on the target side.
        /// Only meaningful when the target return type is a nullable enum.
        /// </summary>
        public object? NullSourceValue { get; set; }

        /// <summary>
        /// Value of the target enum that is produced when the source value is <c>null</c>.
        /// Only meaningful when the source parameter type is a nullable enum.
        /// </summary>
        public object? NullTargetValue { get; set; }
    }

    /// <summary>
    /// Defines an explicit source-&gt;target enum value mapping for special cases.
    /// Can be applied multiple times. Overrides by-name matching for the given source value.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    internal sealed class EnumlyMapValueAttribute : global::System.Attribute
    {
        public EnumlyMapValueAttribute(object source, object target) { }
    }

    /// <summary>
    /// Marks a value of the source enum as intentionally unmapped. Suppresses the
    /// 'no matching target member' diagnostic (EM0001) for that value. At runtime
    /// the ignored value will throw <see cref=""global::System.ArgumentOutOfRangeException""/>
    /// with a message identifying it as explicitly excluded.
    /// Can be applied multiple times.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    internal sealed class EnumlyIgnoreSourceAttribute : global::System.Attribute
    {
        public EnumlyIgnoreSourceAttribute(object value) { }
    }

    /// <summary>
    /// Marks a value of the target enum as intentionally unreachable. Suppresses
    /// the 'target value is not produced by any source mapping' diagnostic
    /// (EM0008) for that value. Can be applied multiple times.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    internal sealed class EnumlyIgnoreTargetAttribute : global::System.Attribute
    {
        public EnumlyIgnoreTargetAttribute(object value) { }
    }
}
";

        private static readonly DiagnosticDescriptor MissingTargetMember = new(id: "EM0001", title: "Source enum value has no matching target member",
            messageFormat:
            "Enum mapping '{0}' -> '{1}': source value '{2}' has no member with the same name in the target enum. Add [EnumlyMapValue({2}, <target>)] to map it explicitly, or [EnumlyIgnoreSource({2})] to exclude it from the mapping.",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor InvalidSignature = new(id: "EM0002", title: "Invalid enum mapping method signature",
            messageFormat:
            "Method '{0}' must be a partial method that takes exactly one (nullable) enum parameter and returns a (nullable) enum type. Example: public static partial TargetEnum Map(SourceEnum value).",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor NullSourceWithNonNullableTarget = new(id: "EM0003", title: "NullSourceValue requires a nullable target",
            messageFormat:
            "Method '{0}' specifies NullSourceValue but the return type is not a nullable enum. Either change the return type to '<TargetEnum>?' or remove NullSourceValue.",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor InvalidNullValue = new(id: "EM0004", title: "Invalid null value",
            messageFormat: "Method '{0}': value '{1}' is not a member of enum '{2}'. Use a declared member of '{2}'.", category: "EnumMapper",
            defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor NullValueWrongType = new(id: "EM0005", title: "Null value has wrong type",
            messageFormat: "Method '{0}': {1} expects a value of enum '{2}' but got a value of type '{3}'. Use a member of '{2}'.", category: "EnumMapper",
            defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor ExplicitMappingWrongType = new(id: "EM0006", title: "Explicit mapping argument has wrong enum type",
            messageFormat: "Method '{0}': EnumlyMapValue {1} expects a value of enum '{2}' but got a value of type '{3}'. The first argument must be a source-enum member, the second a target-enum member.",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor DuplicateExplicitMapping = new(id: "EM0007", title: "Duplicate explicit mapping for source value",
            messageFormat: "Method '{0}': source value '{1}' is mapped explicitly more than once. Remove the duplicate [EnumlyMapValue({1}, ...)] attribute.",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor UnreachableTargetMember = new(id: "EM0008", title: "Target enum value is not reachable from any source value",
            messageFormat:
            "Enum mapping '{0}' -> '{1}': target value '{2}' is not produced by any source value mapping. Add a source value that maps to '{2}' (by name, via [EnumlyMapValue], or via NullTargetValue), or add [EnumlyIgnoreTarget({2})] to mark it as intentionally unreachable.",
            category: "EnumMapper", defaultSeverity: DiagnosticSeverity.Warning, isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor IgnoreValueWrongType = new(id: "EM0009", title: "Ignore-value attribute has wrong enum type",
            messageFormat: "Method '{0}': [{1}] expects a value of enum '{2}' but got a value of type '{3}'. Use a member of '{2}'.", category: "EnumMapper",
            defaultSeverity: DiagnosticSeverity.Error, isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("EnumMapperAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            var classes = context.SyntaxProvider
                .ForAttributeWithMetadataName(EnumlyClassAttributeFqn, predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, ct) => ExtractClass(ctx, ct)).Where(static info => info is not null);

            context.RegisterSourceOutput(classes, static (spc, info) => Emit(spc, info!));
        }

        private static ClassInfo? ExtractClass(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            ct.ThrowIfCancellationRequested();

            if (ctx.TargetSymbol is not INamedTypeSymbol cls)
                return null;

            var methods = new List<MethodInfo>();

            foreach (var member in cls.GetMembers())
            {
                ct.ThrowIfCancellationRequested();

                if (member is not IMethodSymbol m)
                    continue;

                var mapEnumAttr = m.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == EnumlyMapAttributeFqn);
                if (mapEnumAttr is null)
                    continue;

                var location = m.Locations.FirstOrDefault() ?? Location.None;

                if (!m.IsPartialDefinition || m.PartialImplementationPart is not null)
                {
                    methods.Add(MethodInfo.CreateInvalid(m.Name, location));
                    continue;
                }

                if (m.Parameters.Length != 1)
                {
                    methods.Add(MethodInfo.CreateInvalid(m.Name, location));
                    continue;
                }

                var srcEnum = UnwrapEnum(m.Parameters[0].Type, out var srcNullable);
                var tgtEnum = UnwrapEnum(m.ReturnType, out var tgtNullable);

                if (srcEnum is null || tgtEnum is null)
                {
                    methods.Add(MethodInfo.CreateInvalid(m.Name, location));
                    continue;
                }

                var srcMemberNames = srcEnum.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst).Select(f => f.Name).ToArray();
                var tgtMemberNames = tgtEnum.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst).Select(f => f.Name).ToArray();

                var srcPrefix = DetectCommonPrefix(srcMemberNames);
                var tgtPrefix = DetectCommonPrefix(tgtMemberNames);

                var srcMembers = srcMemberNames.Select(n => new EnumMember(n, srcPrefix.Length > 0 ? n.Substring(srcPrefix.Length) : n)).ToArray();
                var tgtMembers = tgtMemberNames.Select(n => new EnumMember(n, tgtPrefix.Length > 0 ? n.Substring(tgtPrefix.Length) : n)).ToArray();

                // Read NullSourceValue / NullTargetValue from attribute-named arguments,
                // including the *type* the user supplied so we can detect type mismatches
                // (e.g. NullSourceValue = Bar.X when the source enum is actually Noo).
                var nullSourceRaw = TryGetNamedArg(mapEnumAttr, "NullSourceValue");
                var nullTargetRaw = TryGetNamedArg(mapEnumAttr, "NullTargetValue");

                var nullSourceTypeMatches = !nullSourceRaw.Specified || (nullSourceRaw.Type is not null && SymbolEqualityComparer.Default.Equals(nullSourceRaw.Type, srcEnum));
                var nullTargetTypeMatches = !nullTargetRaw.Specified || (nullTargetRaw.Type is not null && SymbolEqualityComparer.Default.Equals(nullTargetRaw.Type, tgtEnum));

                // Only resolve to a member name when the type matches — otherwise we'd
                // silently re-interpret e.g. Bar.BarRed (= 0) as Noo.GooNone (= 0).
                var nullSourceMember = nullSourceTypeMatches ? ResolveEnumMemberName(nullSourceRaw.Value, srcEnum) : null;
                var nullTargetMember = nullTargetTypeMatches ? ResolveEnumMemberName(nullTargetRaw.Value, tgtEnum) : null;

                var nullSourceProvidedType = nullSourceRaw.Type?.ToDisplayString() ?? "<unknown>";
                var nullTargetProvidedType = nullTargetRaw.Type?.ToDisplayString() ?? "<unknown>";

                // Collect all [EnumlyMapValue(src, tgt)] attributes for explicit overrides.
                var explicitMappings = new List<ExplicitMapping>();
                var ignoreSource = new List<IgnoreValue>();
                var ignoreTarget = new List<IgnoreValue>();
                foreach (var attr in m.GetAttributes())
                {
                    var attrFqn = attr.AttributeClass?.ToDisplayString();
                    var attrLoc = attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation() ?? location;

                    if (attrFqn == EnumlyMapValueAttributeFqn)
                    {
                        if (attr.ConstructorArguments.Length != 2) continue;

                        var sArg = attr.ConstructorArguments[0];
                        var tArg = attr.ConstructorArguments[1];

                        var srcTypeOk = sArg.Type is not null && SymbolEqualityComparer.Default.Equals(sArg.Type, srcEnum);
                        var tgtTypeOk = tArg.Type is not null && SymbolEqualityComparer.Default.Equals(tArg.Type, tgtEnum);

                        long? srcLong = null, tgtLong = null;
                        try
                        {
                            if (sArg.Value is not null) srcLong = Convert.ToInt64(sArg.Value);
                        }
                        catch
                        {
                            /* ignored */
                        }

                        try
                        {
                            if (tArg.Value is not null) tgtLong = Convert.ToInt64(tArg.Value);
                        }
                        catch
                        {
                            /* ignored */
                        }

                        var sName = srcTypeOk ? ResolveEnumMemberName(srcLong, srcEnum) : null;
                        var tName = tgtTypeOk ? ResolveEnumMemberName(tgtLong, tgtEnum) : null;

                        explicitMappings.Add(new ExplicitMapping(SourceName: sName, TargetName: tName, SourceTypeOk: srcTypeOk, TargetTypeOk: tgtTypeOk,
                            SourceProvidedType: sArg.Type?.ToDisplayString() ?? "<unknown>", TargetProvidedType: tArg.Type?.ToDisplayString() ?? "<unknown>", Location: attrLoc));
                        continue;
                    }

                    if (attrFqn == EnumlyIgnoreSourceAttributeFqn)
                    {
                        if (attr.ConstructorArguments.Length != 1) continue;
                        var arg = attr.ConstructorArguments[0];
                        var typeOk = arg.Type is not null && SymbolEqualityComparer.Default.Equals(arg.Type, srcEnum);
                        long? raw = null;
                        try
                        {
                            if (arg.Value is not null) raw = Convert.ToInt64(arg.Value);
                        }
                        catch
                        {
                            /* ignored */
                        }

                        var name = typeOk ? ResolveEnumMemberName(raw, srcEnum) : null;
                        ignoreSource.Add(new IgnoreValue(name, typeOk, arg.Type?.ToDisplayString() ?? "<unknown>", attrLoc));
                        continue;
                    }

                    if (attrFqn == EnumlyIgnoreTargetAttributeFqn)
                    {
                        if (attr.ConstructorArguments.Length != 1) continue;
                        var arg = attr.ConstructorArguments[0];
                        var typeOk = arg.Type is not null && SymbolEqualityComparer.Default.Equals(arg.Type, tgtEnum);
                        long? raw = null;
                        try
                        {
                            if (arg.Value is not null) raw = Convert.ToInt64(arg.Value);
                        }
                        catch
                        {
                            /* ignored */
                        }

                        var name = typeOk ? ResolveEnumMemberName(raw, tgtEnum) : null;
                        ignoreTarget.Add(new IgnoreValue(name, typeOk, arg.Type?.ToDisplayString() ?? "<unknown>", attrLoc));
                    }
                }

                var srcEnumFqn = srcEnum.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var tgtEnumFqn = tgtEnum.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                methods.Add(new MethodInfo(Name: m.Name, IsStatic: m.IsStatic, Accessibility: AccessibilityString(m.DeclaredAccessibility), ParamName: m.Parameters[0].Name,
                    SourceEnumFqn: srcEnumFqn, TargetEnumFqn: tgtEnumFqn, SourceParamTypeFqn: srcEnumFqn + (srcNullable ? "?" : string.Empty),
                    TargetReturnTypeFqn: tgtEnumFqn + (tgtNullable ? "?" : string.Empty), SourceDisplay: srcEnum.ToDisplayString(), TargetDisplay: tgtEnum.ToDisplayString(),
                    SourceNullable: srcNullable, TargetNullable: tgtNullable, NullSourceMember: nullSourceMember, NullTargetMember: nullTargetMember,
                    NullSourceSpecified: nullSourceRaw.Specified, NullTargetSpecified: nullTargetRaw.Specified, NullSourceTypeMatches: nullSourceTypeMatches,
                    NullTargetTypeMatches: nullTargetTypeMatches, NullSourceProvidedType: nullSourceProvidedType, NullTargetProvidedType: nullTargetProvidedType,
                    NullSourceRawDisplay: nullSourceRaw.Value?.ToString() ?? string.Empty, NullTargetRawDisplay: nullTargetRaw.Value?.ToString() ?? string.Empty,
                    SourceMembers: srcMembers, TargetMembers: tgtMembers, ExplicitMappings: explicitMappings, IgnoreSourceValues: ignoreSource, IgnoreTargetValues: ignoreTarget,
                    Location: location, Invalid: false));
            }

            if (methods.Count == 0)
                return null;

            return new ClassInfo(Namespace: cls.ContainingNamespace.IsGlobalNamespace ? null : cls.ContainingNamespace.ToDisplayString(), ClassName: cls.Name,
                IsStatic: cls.IsStatic, Accessibility: AccessibilityString(cls.DeclaredAccessibility), Methods: methods);
        }

        private static INamedTypeSymbol? UnwrapEnum(ITypeSymbol type, out bool isNullable)
        {
            isNullable = false;
            if (type is not INamedTypeSymbol named)
                return null;

            if (named.IsGenericType
                && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                && named.TypeArguments.Length == 1
                && named.TypeArguments[0] is INamedTypeSymbol inner
                && inner.TypeKind == TypeKind.Enum)
            {
                isNullable = true;
                return inner;
            }

            if (named.TypeKind == TypeKind.Enum)
                return named;

            return null;
        }

        /// <summary>
        /// Detects a common prefix shared by all members of an enum. The prefix is trimmed
        /// back to the last Pascal-case boundary so that for every member the next character
        /// after the prefix is uppercase. Returns "" when no useful prefix is found.
        /// </summary>
        private static string DetectCommonPrefix(string[] memberNames)
        {
            if (memberNames.Length < 2) return string.Empty;

            // Longest common prefix across all member names.
            var lcp = memberNames[0];
            for (var i = 1; i < memberNames.Length; i++)
            {
                var n = memberNames[i];
                var j = 0;
                while (j < lcp.Length && j < n.Length && lcp[j] == n[j]) j++;
                lcp = lcp.Substring(0, j);
                if (lcp.Length == 0) return string.Empty;
            }

            // Trim back to a Pascal-case boundary: every member must continue with an uppercase letter
            // and still have content left. This turns LCP "BarR" into "Bar" for {BarRed, BarRose, BarRoyal}.
            var cut = lcp.Length;
            while (cut > 0)
            {
                var allUpper = true;
                foreach (var n in memberNames)
                {
                    if (cut >= n.Length || !char.IsUpper(n[cut]))
                    {
                        allUpper = false;
                        break;
                    }
                }

                if (allUpper) break;
                cut--;
            }

            return cut > 0 ? lcp.Substring(0, cut) : string.Empty;
        }

        private readonly struct NamedArgInfo(bool specified, long? value, ITypeSymbol? type)
        {
            public bool Specified { get; } = specified;
            public long? Value { get; } = value;
            public ITypeSymbol? Type { get; } = type;
        }

        private static NamedArgInfo TryGetNamedArg(AttributeData attr, string name)
        {
            foreach (var pair in attr.NamedArguments)
            {
                if (pair.Key != name) continue;
                var type = pair.Value.Type;
                if (pair.Value.IsNull || pair.Value.Value is null)
                    return new NamedArgInfo(true, null, type);
                try
                {
                    return new NamedArgInfo(true, Convert.ToInt64(pair.Value.Value), type);
                }
                catch
                {
                    return new NamedArgInfo(true, null, type);
                }
            }

            return new NamedArgInfo(false, null, null);
        }

        private static string? ResolveEnumMemberName(long? rawValue, INamedTypeSymbol enumType)
        {
            if (rawValue is null) return null;
            var target = rawValue.Value;
            foreach (var f in enumType.GetMembers().OfType<IFieldSymbol>())
            {
                if (!f.IsConst || !f.HasConstantValue || f.ConstantValue is null) continue;
                try
                {
                    if (Convert.ToInt64(f.ConstantValue) == target) return f.Name;
                }
                catch
                {
                    // ignored
                }
            }

            return null;
        }

        private static string AccessibilityString(Accessibility a) =>
            a switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.Private => "private",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedAndInternal => "private protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                _ => "internal",
            };

        private static void Emit(SourceProductionContext spc, ClassInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (info.Namespace is not null)
            {
                sb.Append("namespace ").Append(info.Namespace).AppendLine(";");
                sb.AppendLine();
            }

            sb.Append(info.Accessibility).Append(' ');
            if (info.IsStatic) sb.Append("static ");
            sb.Append("partial class ").AppendLine(info.ClassName);
            sb.AppendLine("{");

            var firstMethod = true;
            foreach (var m in info.Methods)
            {
                if (m.Invalid)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(InvalidSignature, m.Location, m.Name));
                    continue;
                }

                // Cross-validate null-value attributes against nullability of source/target.
                // NullSourceValue without a nullable target is a real conflict (the user asks for
                // a null target that the signature can't produce). NullTargetValue without a nullable
                // source is *not* an error — the directive is just unused, since the source can never be null.
                if (m is { NullSourceSpecified: true, TargetNullable: false })
                    spc.ReportDiagnostic(Diagnostic.Create(NullSourceWithNonNullableTarget, m.Location, m.Name));

                // Type checks: if a null-value was specified, its enum type must match the
                // expected side. EM0005 takes precedence over EM0004 — a wrong-type value
                // is the more useful error and EM0004 would be misleading noise.
                if (m is { NullSourceSpecified: true, NullSourceTypeMatches: false })
                {
                    spc.ReportDiagnostic(Diagnostic.Create(NullValueWrongType, m.Location, m.Name, "NullSourceValue", m.SourceDisplay, m.NullSourceProvidedType));
                }
                else if (m is { NullSourceSpecified: true, NullSourceMember: null })
                {
                    spc.ReportDiagnostic(Diagnostic.Create(InvalidNullValue, m.Location, m.Name, m.NullSourceRawDisplay, m.SourceDisplay));
                }

                if (m is { NullTargetSpecified: true, NullTargetTypeMatches: false })
                {
                    spc.ReportDiagnostic(Diagnostic.Create(NullValueWrongType, m.Location, m.Name, "NullTargetValue", m.TargetDisplay, m.NullTargetProvidedType));
                }
                else if (m is { NullTargetSpecified: true, NullTargetMember: null })
                {
                    spc.ReportDiagnostic(Diagnostic.Create(InvalidNullValue, m.Location, m.Name, m.NullTargetRawDisplay, m.TargetDisplay));
                }

                // Validate explicit [EnumlyMapValue] mappings: type must match, and a single source
                // value may not be mapped explicitly twice. Build the override map at the same time.
                var explicitMap = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var em in m.ExplicitMappings)
                {
                    if (!em.SourceTypeOk)
                        spc.ReportDiagnostic(Diagnostic.Create(ExplicitMappingWrongType, em.Location, m.Name, "source", m.SourceDisplay, em.SourceProvidedType));
                    if (!em.TargetTypeOk)
                        spc.ReportDiagnostic(Diagnostic.Create(ExplicitMappingWrongType, em.Location, m.Name, "target", m.TargetDisplay, em.TargetProvidedType));

                    if (em.SourceName is null || em.TargetName is null) continue;

                    if (explicitMap.ContainsKey(em.SourceName))
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(DuplicateExplicitMapping, em.Location, m.Name, em.SourceName));
                        continue;
                    }

                    explicitMap[em.SourceName] = em.TargetName;
                }

                // Validate [EnumlyIgnoreSource] / [EnumlyIgnoreTarget] arguments and collect their member names.
                var ignoredSourceNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (var ig in m.IgnoreSourceValues)
                {
                    if (!ig.TypeOk)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(IgnoreValueWrongType, ig.Location, m.Name, "EnumlyIgnoreSource", m.SourceDisplay, ig.ProvidedType));
                        continue;
                    }

                    if (ig.Name is null) continue;
                    ignoredSourceNames.Add(ig.Name);
                }

                var ignoredTargetNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (var ig in m.IgnoreTargetValues)
                {
                    if (!ig.TypeOk)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(IgnoreValueWrongType, ig.Location, m.Name, "EnumlyIgnoreTarget", m.TargetDisplay, ig.ProvidedType));
                        continue;
                    }

                    if (ig.Name is null) continue;
                    ignoredTargetNames.Add(ig.Name);
                }

                // Determine which source members are "exempt" from the by-name match requirement:
                //   - the explicit null-source member maps to null (target nullable required)
                //   - source members covered by an explicit [EnumlyMapValue]
                //   - source members covered by [EnumlyIgnoreSource]
                // The lookup uses MatchName (stripped enum-name prefix when applicable) so that
                // e.g. Bar.BarRed matches Foo.Red.
                var targetByMatch = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var t in m.TargetMembers) targetByMatch[t.MatchName] = t.Name;
                var nullSrcMember = (m.TargetNullable ? m.NullSourceMember : null);

                foreach (var s in m.SourceMembers)
                {
                    if (s.Name == nullSrcMember) continue;
                    if (explicitMap.ContainsKey(s.Name)) continue;
                    if (ignoredSourceNames.Contains(s.Name)) continue;
                    if (!targetByMatch.ContainsKey(s.MatchName))
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(MissingTargetMember, m.Location, m.SourceDisplay, m.TargetDisplay, s.Name));
                    }
                }

                // Reachability check (EM0008): every target member must be produced by some mapping
                // unless it is explicitly ignored.
                var reachableTargets = new HashSet<string>(StringComparer.Ordinal);
                foreach (var s in m.SourceMembers)
                {
                    if (s.Name == nullSrcMember) continue;
                    if (ignoredSourceNames.Contains(s.Name)) continue;
                    if (explicitMap.TryGetValue(s.Name, out var explicitTgt))
                    {
                        reachableTargets.Add(explicitTgt);
                        continue;
                    }

                    if (targetByMatch.TryGetValue(s.MatchName, out var byNameTgt))
                        reachableTargets.Add(byNameTgt);
                }

                if (m.NullTargetMember is not null) reachableTargets.Add(m.NullTargetMember);

                foreach (var t in m.TargetMembers)
                {
                    if (reachableTargets.Contains(t.Name)) continue;
                    if (ignoredTargetNames.Contains(t.Name)) continue;
                    spc.ReportDiagnostic(Diagnostic.Create(UnreachableTargetMember, m.Location, m.SourceDisplay, m.TargetDisplay, t.Name));
                }

                if (!firstMethod) sb.AppendLine();
                firstMethod = false;

                sb.Append("    ").Append(m.Accessibility).Append(' ');
                if (m.IsStatic) sb.Append("static ");
                sb.Append("partial ").Append(m.TargetReturnTypeFqn).Append(' ').Append(m.Name).Append('(').Append(m.SourceParamTypeFqn).Append(' ').Append(m.ParamName)
                    .AppendLine(")");
                sb.AppendLine("    {");
                sb.Append("        return ").Append(m.ParamName).AppendLine(" switch");
                sb.AppendLine("        {");

                // null-arm: only emit if source is nullable.
                if (m.SourceNullable)
                {
                    if (m.TargetNullable)
                    {
                        sb.AppendLine("            null => null,");
                    }
                    else if (m.NullTargetMember is not null)
                    {
                        sb.Append("            null => ").Append(m.TargetEnumFqn).Append('.').Append(m.NullTargetMember).AppendLine(",");
                    }
                    else
                    {
                        sb.Append("            null => throw new global::System.ArgumentNullException(nameof(").Append(m.ParamName).AppendLine(")),");
                    }
                }

                // explicit source-value -> null (only when target is nullable).
                if (m is { TargetNullable: true, NullSourceMember: not null })
                {
                    sb.Append("            ").Append(m.SourceEnumFqn).Append('.').Append(m.NullSourceMember).AppendLine(" => null,");
                }

                // Mapping arms: explicit [EnumlyMapValue] overrides take precedence over by-name.
                // [EnumlyIgnoreSource] members emit a dedicated arm that throws with a clear message,
                // distinguishing them from truly unknown values that hit the default arm.
                foreach (var s in m.SourceMembers)
                {
                    if (m.TargetNullable && s.Name == m.NullSourceMember) continue;

                    if (ignoredSourceNames.Contains(s.Name))
                    {
                        sb.Append("            ").Append(m.SourceEnumFqn).Append('.').Append(s.Name)
                            .Append(" => throw new global::System.ArgumentOutOfRangeException(nameof(").Append(m.ParamName).Append("), ").Append(m.ParamName)
                            .Append(", \"The value '").Append(m.SourceDisplay).Append('.').Append(s.Name)
                            .Append("' was excluded from the mapping by [EnumlyIgnoreSource].\"),").AppendLine();
                        continue;
                    }

                    string? tgtName = null;
                    if (explicitMap.TryGetValue(s.Name, out var explicitTgt))
                        tgtName = explicitTgt;
                    else if (targetByMatch.TryGetValue(s.MatchName, out var byNameTgt))
                        tgtName = byNameTgt;

                    if (tgtName is null) continue;

                    sb.Append("            ").Append(m.SourceEnumFqn).Append('.').Append(s.Name).Append(" => ").Append(m.TargetEnumFqn).Append('.').Append(tgtName).AppendLine(",");
                }

                sb.Append("            _ => throw new global::System.ArgumentOutOfRangeException(nameof(").Append(m.ParamName).Append("), ").Append(m.ParamName)
                    .Append(", $\"The value of enum \\\"").Append(m.SourceDisplay).Append("\\\" is not supported.\"),").AppendLine();
                sb.AppendLine("        };");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");

            var nsPrefix = info.Namespace?.Replace('.', '_') ?? "global";
            spc.AddSource($"{nsPrefix}.{info.ClassName}.EnumMapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed record ClassInfo(string? Namespace, string ClassName, bool IsStatic, string Accessibility, List<MethodInfo> Methods);

        private sealed record MethodInfo(
            string Name,
            bool IsStatic,
            string Accessibility,
            string ParamName,
            string SourceEnumFqn,
            string TargetEnumFqn,
            string SourceParamTypeFqn,
            string TargetReturnTypeFqn,
            string SourceDisplay,
            string TargetDisplay,
            bool SourceNullable,
            bool TargetNullable,
            string? NullSourceMember,
            string? NullTargetMember,
            bool NullSourceSpecified,
            bool NullTargetSpecified,
            bool NullSourceTypeMatches,
            bool NullTargetTypeMatches,
            string NullSourceProvidedType,
            string NullTargetProvidedType,
            string NullSourceRawDisplay,
            string NullTargetRawDisplay,
            IReadOnlyList<EnumMember> SourceMembers,
            IReadOnlyList<EnumMember> TargetMembers,
            IReadOnlyList<ExplicitMapping> ExplicitMappings,
            IReadOnlyList<IgnoreValue> IgnoreSourceValues,
            IReadOnlyList<IgnoreValue> IgnoreTargetValues,
            Location Location,
            bool Invalid)
        {
            public static MethodInfo CreateInvalid(string name, Location location) =>
                new(name, false, "internal", "value", "", "", "", "", "", "", false, false, null, null, false, false, true, true, "", "", "", "", Array.Empty<EnumMember>(),
                    Array.Empty<EnumMember>(), Array.Empty<ExplicitMapping>(), Array.Empty<IgnoreValue>(), Array.Empty<IgnoreValue>(), location, true);
        }

        private sealed record EnumMember(string Name, string MatchName);

        private sealed record ExplicitMapping(
            string? SourceName,
            string? TargetName,
            bool SourceTypeOk,
            bool TargetTypeOk,
            string SourceProvidedType,
            string TargetProvidedType,
            Location Location);

        private sealed record IgnoreValue(
            string? Name,
            bool TypeOk,
            string ProvidedType,
            Location Location);
    }
}


namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Needed to support the C# 9 init-only feature in older versions of C#
    /// </summary>
    internal static class IsExternalInit { }
}
